language: python
python: 2.7
install:
  - make travis
script: make test
sudo: false
cache:
  directories:
    - eggs
notifications:
  email: guido.stevens@cosent.net
#  irc: "chat.freenode.net#plone.intranet"
